### ISSUE TITLE
Bundle-alike interface

### ISSUE THREAD

**Issue by Addvilz** [php-cds/php-cds-discussion#5]
Symfony has this nice concept of reusable components, e.g. bundles. Any thoughts if something like that might be pulled under a common convention? Would be super cool for having framework independent and container aware share-ables. 

It would probably require a container interface, tho, which might be a issue - we could reuse PSR proposal, however what bugs me is that PSR proposal lacks parameter handling.

**Comment by geggleto** [comment]
I wouldn't mind a standardized bundle interface

**Comment by prisis** [comment]
Take a look on https://github.com/container-interop/service-provider

**Comment by CarwynNelson** [comment]
I think it could type-hint against `container-interop` for container stuff? It seems to be the most widely adopted interface, and I don't think that's going to change any time soon.

The idea of a generic bundle interface that allows bundles to be a bit more framework agnostic is interesting, but I'm not sure how it would work in practice as it tends to be difficult to make actual bundles themselves framework agnostic.

**Comment by shadowhand** [comment]
https://github.com/shadowhand/injector-interop for people that don't like service location. FIG didn't want to have anything to do with it.

**Comment by Addvilz** [comment]
Well, as far as I see in my everyday-Symfony, there tends to be few kinds of bundles - one that provide UI, controllers and functionality (like Sonata, EasyAdmin etc), ones that provide bridges and services for container (like Guzzle bundles) and ones that provide services themselves (like translation bundle). 

The last two types is what I would rather see having at least a bridge to common interface, as there theoretically shouldn't be a lot of coupled stuff, just services. Then again, configuration should be somehow passed so that means either parameter container or service/parameter container. I don't know.

I have this small side project of mine, in which I face the issue that I need a bundle-like interface just without all the Symfony coupling, (for now I have [this interface](https://github.com/protobile/framework/blob/master/src/Protobile/Framework/ConsoleBundle.php), which is also incomplete.

I guess at least 2 methods should be made available from the interface: build (container preparation step, as in Symfony container generation) and run step. As to when to invoke these consumer could decide, but build would be the one registering services.

I'm just brainstorming here, tho.

**Comment by Addvilz** [comment]
Withdrawn.

**Comment by CarwynNelson** [comment]
@Addvilz Is there any particular reason why you have chosen to withdraw your proposal? This looked promising.

**Comment by Addvilz** [comment]
It was a political decision. You are welcome to revive it in a different issue if you feel like doing so. Same with other proposals I withdrew.

**Comment by CarwynNelson** [comment]
Would you be able to elaborate on the specifics of the politics surrounding this decision?

**Comment by marcj** [comment]
@Addvilz I'd be interested in this as well. Maybe talk in gitter?
